### ISSUE TITLE
hello? 

### ISSUE THREAD

**Issue by jonrrivera** [okendo/okendo-reactjs-example#1]

**Comment by mattgarven** [comment]
Hi @jonrrivera, happy to discuss this further if you'd like!

**Comment by jonrrivera** [comment]
awesome, really appreciate your reply. Is there a way to customize the widget style?

**Comment by mattgarven** [comment]
The widget style can be customized quite extensively. Can we move this conversation to email? Send an email to support@okendo.io and I'll keep an eye out for it and get you connected to the right people.
